//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public byte[] Skills { get; set; }
        public Nullable<System.DateTime> LastViewed { get; set; }
    
        public virtual User User { get; set; }
    }
}
